CREATE PROCEDURE findCompanyOfRequirement(@Requirement AS VARCHAR(255))
AS
BEGIN
	SELECT Company.ID, NAME
	FROM COMPANY 
	INNER JOIN EMPLOYEE ON EMPLOYEE.ID_COMPANY = COMPANY.ID
	INNER JOIN RECRUIT_POST_UPLOADER ON EMPLOYEE.ID = RECRUIT_POST_UPLOADER.ID
	INNER JOIN RECRUIT_POST ON RECRUIT_POST_UPLOADER.ID =RECRUIT_POST.ID_UPLOADER
	WHERE RECRUIT_POST.REQUIREMENT = @Requirement
	GROUP BY COMPANY.ID, COMPANY.NAME
END;